--
-- PostgreSQL database dump
--

\restrict 2kSRZJ6wkmNxw3oVLDyAWlCTJaafVThd3wdOSobT45Ft9kewj5o08Z7bQscv6jH

-- Dumped from database version 14.19 (Homebrew)
-- Dumped by pg_dump version 14.19 (Homebrew)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: api_auditorium; Type: TABLE; Schema: public; Owner: trantuanduong
--

CREATE TABLE public.api_auditorium (
    id uuid NOT NULL,
    name character varying(60) NOT NULL,
    standard_row_count integer NOT NULL,
    vip_row_count integer NOT NULL,
    couple_row_count integer NOT NULL,
    seats_per_row integer NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    CONSTRAINT api_auditorium_couple_row_count_check CHECK ((couple_row_count >= 0)),
    CONSTRAINT api_auditorium_seats_per_row_check CHECK ((seats_per_row >= 0)),
    CONSTRAINT api_auditorium_standard_row_count_check CHECK ((standard_row_count >= 0)),
    CONSTRAINT api_auditorium_vip_row_count_check CHECK ((vip_row_count >= 0))
);


ALTER TABLE public.api_auditorium OWNER TO trantuanduong;

--
-- Name: api_booking; Type: TABLE; Schema: public; Owner: trantuanduong
--

CREATE TABLE public.api_booking (
    id uuid NOT NULL,
    status character varying(20) NOT NULL,
    total_amount numeric(12,2) NOT NULL,
    payment_method character varying(30),
    created_at timestamp with time zone NOT NULL,
    expires_at timestamp with time zone,
    user_id uuid NOT NULL,
    showtime_id uuid NOT NULL
);


ALTER TABLE public.api_booking OWNER TO trantuanduong;

--
-- Name: api_genre; Type: TABLE; Schema: public; Owner: trantuanduong
--

CREATE TABLE public.api_genre (
    id uuid NOT NULL,
    name character varying(60) NOT NULL
);


ALTER TABLE public.api_genre OWNER TO trantuanduong;

--
-- Name: api_movie; Type: TABLE; Schema: public; Owner: trantuanduong
--

CREATE TABLE public.api_movie (
    id uuid NOT NULL,
    title character varying(200) NOT NULL,
    duration_min integer NOT NULL,
    rating character varying(10),
    release_date date,
    description text NOT NULL,
    poster_url text NOT NULL,
    CONSTRAINT api_movie_duration_min_check CHECK ((duration_min >= 0))
);


ALTER TABLE public.api_movie OWNER TO trantuanduong;

--
-- Name: api_moviegenre; Type: TABLE; Schema: public; Owner: trantuanduong
--

CREATE TABLE public.api_moviegenre (
    id bigint NOT NULL,
    genre_id uuid NOT NULL,
    movie_id uuid NOT NULL
);


ALTER TABLE public.api_moviegenre OWNER TO trantuanduong;

--
-- Name: api_moviegenre_id_seq; Type: SEQUENCE; Schema: public; Owner: trantuanduong
--

ALTER TABLE public.api_moviegenre ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.api_moviegenre_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: api_payment; Type: TABLE; Schema: public; Owner: trantuanduong
--

CREATE TABLE public.api_payment (
    id uuid NOT NULL,
    amount numeric(12,2) NOT NULL,
    provider character varying(40) NOT NULL,
    external_id character varying(80),
    status character varying(20) NOT NULL,
    paid_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL,
    booking_id uuid NOT NULL
);


ALTER TABLE public.api_payment OWNER TO trantuanduong;

--
-- Name: api_seat; Type: TABLE; Schema: public; Owner: trantuanduong
--

CREATE TABLE public.api_seat (
    id uuid NOT NULL,
    row_label character varying(5) NOT NULL,
    seat_number integer NOT NULL,
    seat_type character varying(10) NOT NULL,
    auditorium_id uuid NOT NULL
);


ALTER TABLE public.api_seat OWNER TO trantuanduong;

--
-- Name: api_showtime; Type: TABLE; Schema: public; Owner: trantuanduong
--

CREATE TABLE public.api_showtime (
    id uuid NOT NULL,
    start_time timestamp with time zone NOT NULL,
    end_time timestamp with time zone NOT NULL,
    base_price numeric(12,2) NOT NULL,
    status character varying(20) NOT NULL,
    auditorium_id uuid NOT NULL,
    movie_id uuid NOT NULL
);


ALTER TABLE public.api_showtime OWNER TO trantuanduong;

--
-- Name: api_ticket; Type: TABLE; Schema: public; Owner: trantuanduong
--

CREATE TABLE public.api_ticket (
    id uuid NOT NULL,
    price numeric(12,2) NOT NULL,
    qr_code character varying(64),
    status character varying(20) NOT NULL,
    booked_at timestamp with time zone NOT NULL,
    booking_id uuid NOT NULL,
    seat_id uuid NOT NULL,
    showtime_id uuid NOT NULL
);


ALTER TABLE public.api_ticket OWNER TO trantuanduong;

--
-- Name: api_user; Type: TABLE; Schema: public; Owner: trantuanduong
--

CREATE TABLE public.api_user (
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL,
    id uuid NOT NULL,
    full_name character varying(100),
    email character varying(254) NOT NULL,
    phone character varying(20),
    role character varying(12) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    date_of_birth date
);


ALTER TABLE public.api_user OWNER TO trantuanduong;

--
-- Name: api_user_groups; Type: TABLE; Schema: public; Owner: trantuanduong
--

CREATE TABLE public.api_user_groups (
    id bigint NOT NULL,
    user_id uuid NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.api_user_groups OWNER TO trantuanduong;

--
-- Name: api_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: trantuanduong
--

ALTER TABLE public.api_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.api_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: api_user_user_permissions; Type: TABLE; Schema: public; Owner: trantuanduong
--

CREATE TABLE public.api_user_user_permissions (
    id bigint NOT NULL,
    user_id uuid NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.api_user_user_permissions OWNER TO trantuanduong;

--
-- Name: api_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: trantuanduong
--

ALTER TABLE public.api_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.api_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: trantuanduong
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO trantuanduong;

--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: trantuanduong
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: trantuanduong
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO trantuanduong;

--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: trantuanduong
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: trantuanduong
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO trantuanduong;

--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: trantuanduong
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: trantuanduong
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id uuid NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO trantuanduong;

--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: trantuanduong
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: trantuanduong
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO trantuanduong;

--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: trantuanduong
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: trantuanduong
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO trantuanduong;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: trantuanduong
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: trantuanduong
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO trantuanduong;

--
-- Name: api_auditorium api_auditorium_name_key; Type: CONSTRAINT; Schema: public; Owner: trantuanduong
--

ALTER TABLE ONLY public.api_auditorium
    ADD CONSTRAINT api_auditorium_name_key UNIQUE (name);


--
-- Name: api_auditorium api_auditorium_pkey; Type: CONSTRAINT; Schema: public; Owner: trantuanduong
--

ALTER TABLE ONLY public.api_auditorium
    ADD CONSTRAINT api_auditorium_pkey PRIMARY KEY (id);


--
-- Name: api_booking api_booking_pkey; Type: CONSTRAINT; Schema: public; Owner: trantuanduong
--

ALTER TABLE ONLY public.api_booking
    ADD CONSTRAINT api_booking_pkey PRIMARY KEY (id);


--
-- Name: api_genre api_genre_name_key; Type: CONSTRAINT; Schema: public; Owner: trantuanduong
--

ALTER TABLE ONLY public.api_genre
    ADD CONSTRAINT api_genre_name_key UNIQUE (name);


--
-- Name: api_genre api_genre_pkey; Type: CONSTRAINT; Schema: public; Owner: trantuanduong
--

ALTER TABLE ONLY public.api_genre
    ADD CONSTRAINT api_genre_pkey PRIMARY KEY (id);


--
-- Name: api_movie api_movie_pkey; Type: CONSTRAINT; Schema: public; Owner: trantuanduong
--

ALTER TABLE ONLY public.api_movie
    ADD CONSTRAINT api_movie_pkey PRIMARY KEY (id);


--
-- Name: api_moviegenre api_moviegenre_movie_id_genre_id_76ce9461_uniq; Type: CONSTRAINT; Schema: public; Owner: trantuanduong
--

ALTER TABLE ONLY public.api_moviegenre
    ADD CONSTRAINT api_moviegenre_movie_id_genre_id_76ce9461_uniq UNIQUE (movie_id, genre_id);


--
-- Name: api_moviegenre api_moviegenre_pkey; Type: CONSTRAINT; Schema: public; Owner: trantuanduong
--

ALTER TABLE ONLY public.api_moviegenre
    ADD CONSTRAINT api_moviegenre_pkey PRIMARY KEY (id);


--
-- Name: api_payment api_payment_booking_id_key; Type: CONSTRAINT; Schema: public; Owner: trantuanduong
--

ALTER TABLE ONLY public.api_payment
    ADD CONSTRAINT api_payment_booking_id_key UNIQUE (booking_id);


--
-- Name: api_payment api_payment_pkey; Type: CONSTRAINT; Schema: public; Owner: trantuanduong
--

ALTER TABLE ONLY public.api_payment
    ADD CONSTRAINT api_payment_pkey PRIMARY KEY (id);


--
-- Name: api_seat api_seat_auditorium_id_row_label_seat_number_c085b67f_uniq; Type: CONSTRAINT; Schema: public; Owner: trantuanduong
--

ALTER TABLE ONLY public.api_seat
    ADD CONSTRAINT api_seat_auditorium_id_row_label_seat_number_c085b67f_uniq UNIQUE (auditorium_id, row_label, seat_number);


--
-- Name: api_seat api_seat_pkey; Type: CONSTRAINT; Schema: public; Owner: trantuanduong
--

ALTER TABLE ONLY public.api_seat
    ADD CONSTRAINT api_seat_pkey PRIMARY KEY (id);


--
-- Name: api_showtime api_showtime_auditorium_id_start_time_684efc01_uniq; Type: CONSTRAINT; Schema: public; Owner: trantuanduong
--

ALTER TABLE ONLY public.api_showtime
    ADD CONSTRAINT api_showtime_auditorium_id_start_time_684efc01_uniq UNIQUE (auditorium_id, start_time);


--
-- Name: api_showtime api_showtime_pkey; Type: CONSTRAINT; Schema: public; Owner: trantuanduong
--

ALTER TABLE ONLY public.api_showtime
    ADD CONSTRAINT api_showtime_pkey PRIMARY KEY (id);


--
-- Name: api_ticket api_ticket_pkey; Type: CONSTRAINT; Schema: public; Owner: trantuanduong
--

ALTER TABLE ONLY public.api_ticket
    ADD CONSTRAINT api_ticket_pkey PRIMARY KEY (id);


--
-- Name: api_ticket api_ticket_showtime_id_seat_id_c45a7e90_uniq; Type: CONSTRAINT; Schema: public; Owner: trantuanduong
--

ALTER TABLE ONLY public.api_ticket
    ADD CONSTRAINT api_ticket_showtime_id_seat_id_c45a7e90_uniq UNIQUE (showtime_id, seat_id);


--
-- Name: api_user api_user_email_key; Type: CONSTRAINT; Schema: public; Owner: trantuanduong
--

ALTER TABLE ONLY public.api_user
    ADD CONSTRAINT api_user_email_key UNIQUE (email);


--
-- Name: api_user_groups api_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: trantuanduong
--

ALTER TABLE ONLY public.api_user_groups
    ADD CONSTRAINT api_user_groups_pkey PRIMARY KEY (id);


--
-- Name: api_user_groups api_user_groups_user_id_group_id_9c7ddfb5_uniq; Type: CONSTRAINT; Schema: public; Owner: trantuanduong
--

ALTER TABLE ONLY public.api_user_groups
    ADD CONSTRAINT api_user_groups_user_id_group_id_9c7ddfb5_uniq UNIQUE (user_id, group_id);


--
-- Name: api_user api_user_pkey; Type: CONSTRAINT; Schema: public; Owner: trantuanduong
--

ALTER TABLE ONLY public.api_user
    ADD CONSTRAINT api_user_pkey PRIMARY KEY (id);


--
-- Name: api_user_user_permissions api_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: trantuanduong
--

ALTER TABLE ONLY public.api_user_user_permissions
    ADD CONSTRAINT api_user_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: api_user_user_permissions api_user_user_permissions_user_id_permission_id_a06dd704_uniq; Type: CONSTRAINT; Schema: public; Owner: trantuanduong
--

ALTER TABLE ONLY public.api_user_user_permissions
    ADD CONSTRAINT api_user_user_permissions_user_id_permission_id_a06dd704_uniq UNIQUE (user_id, permission_id);


--
-- Name: api_user api_user_username_key; Type: CONSTRAINT; Schema: public; Owner: trantuanduong
--

ALTER TABLE ONLY public.api_user
    ADD CONSTRAINT api_user_username_key UNIQUE (username);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: trantuanduong
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: trantuanduong
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: trantuanduong
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: trantuanduong
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: trantuanduong
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: trantuanduong
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: trantuanduong
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: trantuanduong
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: trantuanduong
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: trantuanduong
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: trantuanduong
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: api_auditorium_name_af3b8bc3_like; Type: INDEX; Schema: public; Owner: trantuanduong
--

CREATE INDEX api_auditorium_name_af3b8bc3_like ON public.api_auditorium USING btree (name varchar_pattern_ops);


--
-- Name: api_booking_expires_651e73_idx; Type: INDEX; Schema: public; Owner: trantuanduong
--

CREATE INDEX api_booking_expires_651e73_idx ON public.api_booking USING btree (expires_at);


--
-- Name: api_booking_showtim_c4c32e_idx; Type: INDEX; Schema: public; Owner: trantuanduong
--

CREATE INDEX api_booking_showtim_c4c32e_idx ON public.api_booking USING btree (showtime_id);


--
-- Name: api_booking_showtime_id_2b40e217; Type: INDEX; Schema: public; Owner: trantuanduong
--

CREATE INDEX api_booking_showtime_id_2b40e217 ON public.api_booking USING btree (showtime_id);


--
-- Name: api_booking_user_id_0beb30da; Type: INDEX; Schema: public; Owner: trantuanduong
--

CREATE INDEX api_booking_user_id_0beb30da ON public.api_booking USING btree (user_id);


--
-- Name: api_booking_user_id_cfdf50_idx; Type: INDEX; Schema: public; Owner: trantuanduong
--

CREATE INDEX api_booking_user_id_cfdf50_idx ON public.api_booking USING btree (user_id);


--
-- Name: api_genre_name_321d7007_like; Type: INDEX; Schema: public; Owner: trantuanduong
--

CREATE INDEX api_genre_name_321d7007_like ON public.api_genre USING btree (name varchar_pattern_ops);


--
-- Name: api_moviegenre_genre_id_e9ff3de3; Type: INDEX; Schema: public; Owner: trantuanduong
--

CREATE INDEX api_moviegenre_genre_id_e9ff3de3 ON public.api_moviegenre USING btree (genre_id);


--
-- Name: api_moviegenre_movie_id_a4d5ccb0; Type: INDEX; Schema: public; Owner: trantuanduong
--

CREATE INDEX api_moviegenre_movie_id_a4d5ccb0 ON public.api_moviegenre USING btree (movie_id);


--
-- Name: api_payment_booking_a0e9be_idx; Type: INDEX; Schema: public; Owner: trantuanduong
--

CREATE INDEX api_payment_booking_a0e9be_idx ON public.api_payment USING btree (booking_id);


--
-- Name: api_seat_auditorium_id_6213d2ec; Type: INDEX; Schema: public; Owner: trantuanduong
--

CREATE INDEX api_seat_auditorium_id_6213d2ec ON public.api_seat USING btree (auditorium_id);


--
-- Name: api_showtim_auditor_3717c2_idx; Type: INDEX; Schema: public; Owner: trantuanduong
--

CREATE INDEX api_showtim_auditor_3717c2_idx ON public.api_showtime USING btree (auditorium_id, start_time);


--
-- Name: api_showtim_movie_i_043b6b_idx; Type: INDEX; Schema: public; Owner: trantuanduong
--

CREATE INDEX api_showtim_movie_i_043b6b_idx ON public.api_showtime USING btree (movie_id);


--
-- Name: api_showtime_auditorium_id_50f59683; Type: INDEX; Schema: public; Owner: trantuanduong
--

CREATE INDEX api_showtime_auditorium_id_50f59683 ON public.api_showtime USING btree (auditorium_id);


--
-- Name: api_showtime_movie_id_e8eff6d5; Type: INDEX; Schema: public; Owner: trantuanduong
--

CREATE INDEX api_showtime_movie_id_e8eff6d5 ON public.api_showtime USING btree (movie_id);


--
-- Name: api_ticket_booking_id_be136328; Type: INDEX; Schema: public; Owner: trantuanduong
--

CREATE INDEX api_ticket_booking_id_be136328 ON public.api_ticket USING btree (booking_id);


--
-- Name: api_ticket_seat_id_a80d9c80; Type: INDEX; Schema: public; Owner: trantuanduong
--

CREATE INDEX api_ticket_seat_id_a80d9c80 ON public.api_ticket USING btree (seat_id);


--
-- Name: api_ticket_showtim_31e4c3_idx; Type: INDEX; Schema: public; Owner: trantuanduong
--

CREATE INDEX api_ticket_showtim_31e4c3_idx ON public.api_ticket USING btree (showtime_id);


--
-- Name: api_ticket_showtime_id_c02c9f36; Type: INDEX; Schema: public; Owner: trantuanduong
--

CREATE INDEX api_ticket_showtime_id_c02c9f36 ON public.api_ticket USING btree (showtime_id);


--
-- Name: api_user_email_9ef5afa6_like; Type: INDEX; Schema: public; Owner: trantuanduong
--

CREATE INDEX api_user_email_9ef5afa6_like ON public.api_user USING btree (email varchar_pattern_ops);


--
-- Name: api_user_groups_group_id_3af85785; Type: INDEX; Schema: public; Owner: trantuanduong
--

CREATE INDEX api_user_groups_group_id_3af85785 ON public.api_user_groups USING btree (group_id);


--
-- Name: api_user_groups_user_id_a5ff39fa; Type: INDEX; Schema: public; Owner: trantuanduong
--

CREATE INDEX api_user_groups_user_id_a5ff39fa ON public.api_user_groups USING btree (user_id);


--
-- Name: api_user_user_permissions_permission_id_305b7fea; Type: INDEX; Schema: public; Owner: trantuanduong
--

CREATE INDEX api_user_user_permissions_permission_id_305b7fea ON public.api_user_user_permissions USING btree (permission_id);


--
-- Name: api_user_user_permissions_user_id_f3945d65; Type: INDEX; Schema: public; Owner: trantuanduong
--

CREATE INDEX api_user_user_permissions_user_id_f3945d65 ON public.api_user_user_permissions USING btree (user_id);


--
-- Name: api_user_username_cf4e88d2_like; Type: INDEX; Schema: public; Owner: trantuanduong
--

CREATE INDEX api_user_username_cf4e88d2_like ON public.api_user USING btree (username varchar_pattern_ops);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: trantuanduong
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: trantuanduong
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: trantuanduong
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: trantuanduong
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: trantuanduong
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: trantuanduong
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: trantuanduong
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: trantuanduong
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: api_booking api_booking_showtime_id_2b40e217_fk_api_showtime_id; Type: FK CONSTRAINT; Schema: public; Owner: trantuanduong
--

ALTER TABLE ONLY public.api_booking
    ADD CONSTRAINT api_booking_showtime_id_2b40e217_fk_api_showtime_id FOREIGN KEY (showtime_id) REFERENCES public.api_showtime(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: api_booking api_booking_user_id_0beb30da_fk_api_user_id; Type: FK CONSTRAINT; Schema: public; Owner: trantuanduong
--

ALTER TABLE ONLY public.api_booking
    ADD CONSTRAINT api_booking_user_id_0beb30da_fk_api_user_id FOREIGN KEY (user_id) REFERENCES public.api_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: api_moviegenre api_moviegenre_genre_id_e9ff3de3_fk_api_genre_id; Type: FK CONSTRAINT; Schema: public; Owner: trantuanduong
--

ALTER TABLE ONLY public.api_moviegenre
    ADD CONSTRAINT api_moviegenre_genre_id_e9ff3de3_fk_api_genre_id FOREIGN KEY (genre_id) REFERENCES public.api_genre(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: api_moviegenre api_moviegenre_movie_id_a4d5ccb0_fk_api_movie_id; Type: FK CONSTRAINT; Schema: public; Owner: trantuanduong
--

ALTER TABLE ONLY public.api_moviegenre
    ADD CONSTRAINT api_moviegenre_movie_id_a4d5ccb0_fk_api_movie_id FOREIGN KEY (movie_id) REFERENCES public.api_movie(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: api_payment api_payment_booking_id_cbb84fcd_fk_api_booking_id; Type: FK CONSTRAINT; Schema: public; Owner: trantuanduong
--

ALTER TABLE ONLY public.api_payment
    ADD CONSTRAINT api_payment_booking_id_cbb84fcd_fk_api_booking_id FOREIGN KEY (booking_id) REFERENCES public.api_booking(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: api_seat api_seat_auditorium_id_6213d2ec_fk_api_auditorium_id; Type: FK CONSTRAINT; Schema: public; Owner: trantuanduong
--

ALTER TABLE ONLY public.api_seat
    ADD CONSTRAINT api_seat_auditorium_id_6213d2ec_fk_api_auditorium_id FOREIGN KEY (auditorium_id) REFERENCES public.api_auditorium(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: api_showtime api_showtime_auditorium_id_50f59683_fk_api_auditorium_id; Type: FK CONSTRAINT; Schema: public; Owner: trantuanduong
--

ALTER TABLE ONLY public.api_showtime
    ADD CONSTRAINT api_showtime_auditorium_id_50f59683_fk_api_auditorium_id FOREIGN KEY (auditorium_id) REFERENCES public.api_auditorium(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: api_showtime api_showtime_movie_id_e8eff6d5_fk_api_movie_id; Type: FK CONSTRAINT; Schema: public; Owner: trantuanduong
--

ALTER TABLE ONLY public.api_showtime
    ADD CONSTRAINT api_showtime_movie_id_e8eff6d5_fk_api_movie_id FOREIGN KEY (movie_id) REFERENCES public.api_movie(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: api_ticket api_ticket_booking_id_be136328_fk_api_booking_id; Type: FK CONSTRAINT; Schema: public; Owner: trantuanduong
--

ALTER TABLE ONLY public.api_ticket
    ADD CONSTRAINT api_ticket_booking_id_be136328_fk_api_booking_id FOREIGN KEY (booking_id) REFERENCES public.api_booking(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: api_ticket api_ticket_seat_id_a80d9c80_fk_api_seat_id; Type: FK CONSTRAINT; Schema: public; Owner: trantuanduong
--

ALTER TABLE ONLY public.api_ticket
    ADD CONSTRAINT api_ticket_seat_id_a80d9c80_fk_api_seat_id FOREIGN KEY (seat_id) REFERENCES public.api_seat(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: api_ticket api_ticket_showtime_id_c02c9f36_fk_api_showtime_id; Type: FK CONSTRAINT; Schema: public; Owner: trantuanduong
--

ALTER TABLE ONLY public.api_ticket
    ADD CONSTRAINT api_ticket_showtime_id_c02c9f36_fk_api_showtime_id FOREIGN KEY (showtime_id) REFERENCES public.api_showtime(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: api_user_groups api_user_groups_group_id_3af85785_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: trantuanduong
--

ALTER TABLE ONLY public.api_user_groups
    ADD CONSTRAINT api_user_groups_group_id_3af85785_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: api_user_groups api_user_groups_user_id_a5ff39fa_fk_api_user_id; Type: FK CONSTRAINT; Schema: public; Owner: trantuanduong
--

ALTER TABLE ONLY public.api_user_groups
    ADD CONSTRAINT api_user_groups_user_id_a5ff39fa_fk_api_user_id FOREIGN KEY (user_id) REFERENCES public.api_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: api_user_user_permissions api_user_user_permis_permission_id_305b7fea_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: trantuanduong
--

ALTER TABLE ONLY public.api_user_user_permissions
    ADD CONSTRAINT api_user_user_permis_permission_id_305b7fea_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: api_user_user_permissions api_user_user_permissions_user_id_f3945d65_fk_api_user_id; Type: FK CONSTRAINT; Schema: public; Owner: trantuanduong
--

ALTER TABLE ONLY public.api_user_user_permissions
    ADD CONSTRAINT api_user_user_permissions_user_id_f3945d65_fk_api_user_id FOREIGN KEY (user_id) REFERENCES public.api_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: trantuanduong
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: trantuanduong
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: trantuanduong
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: trantuanduong
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_api_user_id; Type: FK CONSTRAINT; Schema: public; Owner: trantuanduong
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_api_user_id FOREIGN KEY (user_id) REFERENCES public.api_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

\unrestrict 2kSRZJ6wkmNxw3oVLDyAWlCTJaafVThd3wdOSobT45Ft9kewj5o08Z7bQscv6jH

